# Generated by Django 4.2.4 on 2023-10-06 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msg',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(default='hello', max_length=1000),
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
